### ISSUE TITLE
No information provided on how to "code" a pattern

### ISSUE THREAD

**Issue by duggym122** [enckse/pyxstitch#1]
Is there an expected format or syntax to use when creating pattern programs? I think what is escaping me here is how to create a file to feed into pyxstitch to create a given image. For example, do you have reference files for the completed projects posted on your website?

**Comment by enckse** [comment]
hmmm some of my documentation needs to be updated to point at patterns that are only what `pyxstitch` can do. `pyxstitch` itself is only capable of taking "source code" in and producing patterns to actually stitch "code" like [this](https://crossstitch.info/resources/current/history.jpg).

The readme should point at a specific example of these and not at "normal" patterns I create (I used kxstitch for other patterns).
